import axios from 'axios';
import mumaker from 'mumaker';

export default[
    {
    name: 'textmaker',
    aliases: ['texteffect', 'logo'],
    category: 'image',
    description: 'Create text effects and logos',
    usage: '.textmaker <type> <text>',
    execute: async (sock, message, args, context) => {
        const { chatId, reply, react, rawText } = context;

        const parts = rawText.split(' ').slice(1);
        if (parts.length < 2) {
            return await reply("Please provide effect type and text to generate\n\nAvailable effects:\nmetallic, ice, snow, impressive, matrix, light, neon, devil, purple, thunder, leaves, 1917, arena, hacker, sand, blackpink, glitch, fire\n\nExample: `.textmaker metallic Nick`",{quoted: global.textmaker});
        }

        const type = parts[0].toLowerCase();
        const text = parts.slice(1).join(' ');

        const validTypes = ['metallic', 'ice', 'snow', 'impressive', 'matrix', 'light', 'neon', 'devil', 'purple', 'thunder', 'leaves', '1917', 'arena', 'hacker', 'sand', 'blackpink', 'glitch', 'fire'];
        
        if (!validTypes.includes(type)) {
            return await reply(`Invalid effect type. Available effects:\n${validTypes.join(', ')}`,{quoted: global.textmaker});
        }

        try {
            await react('🎨');

            let result;
            const typeUrls = {
                metallic: "https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html",
                ice: "https://en.ephoto360.com/ice-text-effect-online-101.html",
                snow: "https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html",
                impressive: "https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html",
                matrix: "https://en.ephoto360.com/matrix-text-effect-154.html",
                light: "https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html",
                neon: "https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html",
                devil: "https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html",
                purple: "https://en.ephoto360.com/purple-text-effect-online-100.html",
                thunder: "https://en.ephoto360.com/thunder-text-effect-online-97.html",
                leaves: "https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html",
                '1917': "https://en.ephoto360.com/1917-style-text-effect-523.html",
                arena: "https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html",
                hacker: "https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html",
                sand: "https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html",
                blackpink: "https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html",
                glitch: "https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html",
                fire: "https://en.ephoto360.com/flame-lettering-effect-372.html"
            };

            result = await mumaker.ephoto(typeUrls[type], text);

            if (!result || !result.image) {
                throw new Error('No image URL received from the API');
            }

            await sock.sendMessage(chatId, {
                image: { url: result.image },
                caption: `✨${type.toUpperCase()} Effect\n\nText: "${text}"\nGenerated by Gift Bot`,
                ...context.channelInfo
            },{quoted: global.textmaker});

            await react('✅');

        } catch (error) {
            await reply(`❌ Error generating ${type} effect. Please try again later.`,{quoted: global.textmaker});
        }
    }
},
    
{
    name: 'fliptext',
    aliases: ['flip'],
    category: 'TOOLS MENU',
    execute: async (sock, message, args, context) => {
        const prefix = global.prefix;
        
        if (args.length < 2) return context.reply(`Example:\n${prefix}fliptext Tylor`,{quoted: global.fliptext});
        let flips = args.slice(1).join(" ");
        let flipx = flips.split("").reverse().join("");
        context.reply(`Normal:\n${flips}\n\nFlip:\n${flipx}`,{quoted: global.fliptext});
    }
}
];
